import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import NavHeightProvider from "@/components/NavHeightProvider/NavHeightProvider";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        {/* NavHeightProvider sets --navbar-height CSS variable based on the rendered navbar */}
        <div id="nav-height-provider-root" />
        <NavHeightProvider />
        {children}
        <div className="p-4">
          <Footer />
        </div>
      </body>
    </html>
  );
}
